### ISSUE TITLE
rewrite error

### ISSUE THREAD

**Issue by jacsonp** [campanhacompleta/parlamentar#12]
Precisa recarregar as regras de rewrite quando o novo post type é adicionado,

**Comment by jacsonp** [comment]
5555b1e86f4695bbe096fef108a89c48bb6933e8 corrige quando o plugin é ativado fora de um ambiente WPMU
f0da7be47ff5d4245690013bc31a906b03c7658c checa e corrige quando em wpmu

**Comment by eduardozulian** [comment]
:punch:
