### ISSUE TITLE
Campo data de nascimento precisa de um date picker

### ISSUE THREAD

**Issue by eduardozulian** [campanhacompleta/parlamentar#21]

**Comment by jpmehl** [comment]
Aqui poderia pegar a idade automaticamnete e colocar entre parenteses, o
que acha?

2015-10-14 14:46 GMT-03:00 Eduardo Zulian notifications@github.com:

> Closed #21 https://github.com/campanhacompleta/parlamentar/issues/21
> via 1ff1b94
> https://github.com/campanhacompleta/parlamentar/commit/1ff1b948ccfaedeed11b3a53b64ca8e8fc99f798
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/campanhacompleta/parlamentar/issues/21#event-435498944
> .

## 

João Paulo Mehl
Ethymos Soluções em Web
www.ethymos.com.br
(41)3077-4163 / 9221-1909

**Comment by eduardozulian** [comment]
Acho legal! Abre uma issue separada pra isso, @jpmehl?
