### ISSUE TITLE
Mudar nome de campo Tipo para Cargo

### ISSUE THREAD

**Issue by eduardozulian** [campanhacompleta/parlamentar#22]
Acabei criando uma taxonomia bem genérica para do parlamentar (deputado estadual, federal etc) chamada **Tipo**. Acho esse nome genérico demais e proponho trocarmos para **Cargo** (_role_, em inglês).

@jmehl, o que acha?

**Comment by jpmehl** [comment]
Acho que "cargo" é bom. toca ficha.
