### ISSUE TITLE
Imagens não uniformes em Vereador

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/parlamentar#34]
A página que puxa a categoria Vereador não está mostrando as imagens com uniformidade, conforme as páginas de Deputado Estadual e Federal.

**Comment by eduardozulian** [comment]
Feito!

As imagens dos parlamentares precisarão ter pelo menos 640 px de largura por 480 de altura. Caso elas não atendam a esse tamanho, teremos problemas com a proporção delas.

@anapaulabrasa, é possível usar o [Renegerate Thumbnails](https://br.wordpress.org/plugins/regenerate-thumbnails/) para atualizar a proporção das imagens antigas (isso após a atualização do código em produção). O plugin está disponível em WP-Admin > Ferramentas.

**Comment by anapaulabrasa** [comment]
@eduardozulian não entendi direito o uso do plugin. Qual código em produção?

**Comment by eduardozulian** [comment]
O plugin gera novamente todos os tamanhos de imagens. Neste caso, ele readequa as proporções das imagens que estão na biblioteca de mídia para aquelas definidas dentro do tema.

A atualização do código em produção significa: quando a gente subir as novas mudanças. :smile:
