### ISSUE TITLE
Página Vereador mostrando categoria deputados

### ISSUE THREAD

**Issue by anapaulabrasa** [campanhacompleta/parlamentar#35]
Página que puxa categorização de Vereadores está também puxando deputados.

**Comment by eduardozulian** [comment]
Funcionando. 

Simplesmente troquei o atributo `type` por `role`, como consta na [versão atualizada](https://github.com/campanhacompleta/parlamentar#shortcodes) do README.

Agora ficou assim:  `[parlamentar role="vereador"]`
